name: FOSSA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  fossa:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install dependencies
        run: ./gradlew build

      - name: Run FOSSA scan and upload build data
        uses: fossas/fossa-action@09bcf127dc0ccb4b5a023f6f906728878e8610ba # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          branch: ${{ github.ref_name }}

      - name: Run FOSSA tests
        uses: fossas/fossa-action@09bcf127dc0ccb4b5a023f6f906728878e8610ba # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
